### ISSUE TITLE
scripted effects doesn't recognize $bare$ arguments

### ISSUE THREAD

**Issue by maxice8** [cwtools/cwtools-eu4-config#112]
The following code complains that `$effect$` is not valid in `while = { }`, 

```
for = {
  set_variable = {
    which = ForLoopCounter
    value = $amount$
  }

  while = {
    limit = {
      check_variable = {
        which = ForLoopCounter
        value = 1
      }
    }
    $effect$
    subtract_variable = {
      which = ForLoopCounter
      value = 1
    }
  }
}
```

![image](https://user-images.githubusercontent.com/30738253/178478606-bda7f166-296a-4379-b3ff-d88c4c405eac.png)

All usages of it in the mod are `for = { amount = X effect = "code that does effect here" }`

**Comment by 17blue17** [comment]
Can you please go to the Paradox eu4 forum then to user mods then to the thread near the top for cwtools?   Normally only one person updates for eu4 and that has been me but I have been sick so I appreciate your help but it would be nice to coordinate.   I had some work done on eu4 1.34 and I had to toss it all out hoping yours would be more complete.

**Comment by maxice8** [comment]
Done

**Comment by 17blue17** [comment]
cwtools has problems with scripted effects and scripted triggers.  This is listed under known issues on the forum.  Basically a lot of items got broken when Pararadox started using [[ ] stuff.   Dayshine even turned off checking for these files.   I have had some minor luck adding to the rules file for scripted at the end some force code for a few items.   Some things we can force many items we can not.
