### ISSUE TITLE
Mission SCA_Lithuania_Missions

### ISSUE THREAD

**Issue by 17blue17** [cwtools/cwtools-eu4-config#177]
tooltip = { 
				add_province_modifier = {
					name = lit_centers_urbanization_modifier
					duration = 7300 
				}
			}

complains it is in the wrong scope is country expect province - not sure if bug or cwtools problem

**Comment by maxice8** [comment]
That should be okay, if you look closely you will see it is inside a `tooltip = { }`, that is used extensively in Ante Bellum (the mod I am a contributor to) to display the modifier a province/country will get.


If you look more into the code you can see it has a custom_tooltip before it so it will show

```
<custom_tooltip>:
<modifier>
```

Which looks very nice to the user.
 
![image](https://user-images.githubusercontent.com/30738253/194738608-c185719a-4ab0-492a-9631-2f69f3366225.png)

**Comment by 17blue17** [comment]
so will you fix cwtools for this? As I have no idea how to fix it.

**Comment by maxice8** [comment]
It is a hard call, if you take in a very strict sense wrong, tooltip uses the country scope.

But it is being used as intended with an effect that was intended by Paradox (and was and currently is used extensively in Ante Bellum and other mods before it).

So we have two options:

1. make the `tooltip = { }` accept any scopes by using `## push_scope = any`, this makes so it does not check if the province modifier is correct but it also disables any checking of correct scopes inside it.
2. Ignore it, it is an error in the strict sense but not by the intent of the modder and now, even PDX.

**Comment by 17blue17** [comment]
It sounds like Paradox thinks it is ok and you say it works so most likely Paradox will keep making more of them so we will end up with users of cwtools facing walls of red orange errors and unable to spot anything important.  

Reminds me of the old validator utility which I used to help support where a user would be faced with 1000's of false errors and only the most tech savvy wizards would know what to ignore and what to fix.  The experts on the forum did not want anything added to the database rules unless it was 1000000% proven and then these same experts refused to help test or share their knowledge.   The result was that when cwtools came along the author of the validator shut it down.   Now I think they are trying to bring it back as it could do some things better but they are having the same old problem of getting information with almost no help.  

Personally I think we should make the error go away so the average user can focus on more important things. Almost all the new missions are walls of red orange errors in cwtools.

I am in pain with my neck and my knees and I am not thinking well lately.  I just want 1.34 done.  I will leave it up to you but if you leave it then it will most likely remain an error forever as I don't understand tooltips.
