### ISSUE TITLE
Recognize defined_text in customizable localisation as valid commands

### ISSUE THREAD

**Issue by maxice8** [cwtools/cwtools-eu4-config#233]
I am using `defined_text = { name = X }` in customizable_localisation and it would be nice if it recognized those keys

**Comment by 17blue17** [comment]
Only way it happens is if you post on discord and ask Dayshine and he does not seem to be answering anyone......  Maybe Caligula has a suggestion as a work around?   I doubt either checks or reads Eu4 issues here.

**Comment by maxice8** [comment]
It is not a question of needing support, just someone needs to create the enum code to support it.

see #234 for my attempt at an implementation
