### ISSUE TITLE
Series of modifiers (and conditions) that are unexpected (whereas the game process them correctly)

### ISSUE THREAD

**Issue by Melvasul** [cwtools/cwtools-eu4-config#26]
I posted this issue on the main cwtools, but maybe I should have done it here:

https://github.com/cwtools/cwtools/issues/33

Hello, I went through a serious of modifiers and conditions that are `unexpected` by the extension, whereas the game process it correctly, I will post only one photo to show you what I mean:
![2020 07 12-01 41](https://user-images.githubusercontent.com/11297488/87235815-cf865780-c3e0-11ea-8cec-d4653efd5e51.png)

1. movement_speed_onto_off_boat_modifier
2. accept_vassalization_reasons
3. institution_growth
4. extra_manpower_at_religious_war = yes (I recall this working, although I may be wrong)

Conditions:
1. ADM/DIP/MIL (used to refer the current adm/dip/mil stat of the ruler)
2. has_adm_advisor_1/2/3 as well as has_dip_advisor_1/2/3 and has_mil_advisor_1/2/3

Effects:
1. join_all_offensive_wars_of = TAG
2. join_all_defensive_wars_of = TAG

if I'll ever find others I'll write them down :)

unrest (both province and global) can accept negative value
![2020 07 20-10 19](https://user-images.githubusercontent.com/11297488/87915542-99954300-ca72-11ea-95ef-3d9cc35ea7af.png)

**Comment by Melvasul** [comment]
Convert Ruler to general expects a yes, not an integer
![immagine](https://user-images.githubusercontent.com/11297488/115994565-d67d0000-a5d7-11eb-9e65-d5a89b1c27ac.png)

ADM/DIP/MIL are the ruler_adm ruler_dip and ruler_mil
![immagine](https://user-images.githubusercontent.com/11297488/115994585-f7455580-a5d7-11eb-8710-861f16d3c683.png)

**Comment by 17blue17** [comment]
I think I fixed the ones I understand.  Best to make requests on the eu4 paradox forum cwtools thread
