### ISSUE TITLE
Allow elector to be used in hre_reform modding

### ISSUE THREAD

**Issue by EmperorNuclear** [cwtools/cwtools-eu4-config#268]
Straight forward, as the title says. See images if confused.

![Screenshot 2023-04-11 133745](https://user-images.githubusercontent.com/114454346/231282500-70ab6c9f-7a24-40de-aa95-d6d717914089.png)

![Screenshot 2023-04-11 133802](https://user-images.githubusercontent.com/114454346/231282532-4d583afd-55f5-409c-8faa-af1355f4e958.png)

**Comment by maxice8** [comment]
Done in #269, if possible test it to see if it works as expected
