### ISSUE TITLE
Province IDs are treated as effects in certain cases

### ISSUE THREAD

**Issue by theolaa** [cwtools/cwtools-eu4-config#284]
As you can see, province IDs are quite problematic according to CW Tools. These are all perfectly functional provinces, as far as the game is concerned.

![image](https://user-images.githubusercontent.com/38194309/235599263-98cf7aa7-fed4-4670-954a-b0b4b79bf9dd.png)

The corresponding error when I hover one of them (appears in the output window)
`[Info  - 11:52:22 PM] symbolInfoAtPos common/colonial_regions/00_colonial_regions.txt c:\Users\theol\Documents\Paradox Interactive\Europa Universalis IV\mod\Elder-Scrolls-Universalis\common\colonial_regions\00_colonial_regions.txt
Looking for effect "1551" in the 1436 effects loaded`

When I hover the `provinces` entry, it gives this error:

![image](https://user-images.githubusercontent.com/38194309/235599620-61c4c6fd-6b49-407a-9632-bfe88b2faf1c.png)

So it seems to not think that those are `province_id` types, but rather effects. Very puzzling to me. Hopefully someone knows what's up haha.

**Comment by maxice8** [comment]
CWTools looks at `map/positions.txt` to find out all the provinces, are they there ?

**Comment by theolaa** [comment]
@maxice8 yes, it is included. Sorry, I should have written that originally. You can see my project here: https://codeberg.org/Aetherial-Mods/Elder-Scrolls-Universalis/src/branch/master/map/positions.txt

**Comment by 17blue17** [comment]
I downloaded your mod and then created a .mod file as I do not know if cwtools knows about descriptor files.   The .mod file I used:
[elder-scrolls-universalis.zip](https://github.com/cwtools/cwtools-eu4-config/files/11375306/elder-scrolls-universalis.zip)

I see no problems with the provinces.  See attached.   So I think the problem was a missing or .mod file or path in the .mod file.   CWTools expects a local mod not a steam mod using a simple path.
  
![Untitled-1](https://user-images.githubusercontent.com/75548706/235722498-9af68d4e-fe35-4a5f-8bde-a9580bad9906.jpg)

**Comment by theolaa** [comment]
Interesting, are you opening cwtools on the mod itself, or the eu4 mod folder? That might be making the difference

**Comment by 17blue17** [comment]
You always open cwtools on the your documents mod folder.  So for me D:\Users\Steven\My Documents\Paradox Interactive\Europa Universalis IV\mod

In the extension settings for cwtools you specify where the game is so for eu4 for me:  D:\Steam\steamapps\common\Europa Universalis IV

**Comment by 17blue17** [comment]
also always select and open in cwtools a .txt file from your mod so it can start validating.  It does strange things if you select a non .txt file

**Comment by theolaa** [comment]
Ok, I'll have to try it that way later. I was always under the impression you could do either way, and I always opted to just open each mod since it makes my workspace cleaner than opening all of them at once. I'll let you know if it fixes the issue.

**Comment by theolaa** [comment]
Man, are we sure that's right, opening it in the `Documents/EU4/mod` folder directly? I can't get it to work at all there, and I saw the extension using over 7GB of RAM lol.

Here's the output from the last time I tried to run it: 
[vs code log.txt](https://github.com/cwtools/cwtools-eu4-config/files/11378497/vs.code.log.txt)

**Comment by 17blue17** [comment]
Yes.   Did you use the .mod file I uploaded?  Is the .mod file outside your mod but in the mod directory? Did you open a .txt file from your mod to get it to start?  At this point ask for more help on the cwtools thread on the stellaris modding den.  The provinces are not broken.
