### ISSUE TITLE
False Error Notices

### ISSUE THREAD

**Issue by EmperorNuclear** [cwtools/cwtools-eu4-config#287]
exile_consort_as and set_consort is marked as an error when used in if statements:
![Screenshot 2023-05-15 165836](https://github.com/cwtools/cwtools-eu4-config/assets/114454346/e4fdaefd-56bb-4a35-9469-d07089f7573f)

Scripted Effects parameters s giving an incorrect error (new_tag scopes to a country):
![Screenshot 2023-05-15 165844](https://github.com/cwtools/cwtools-eu4-config/assets/114454346/db91b04b-3d9c-4869-935c-e0a02dbf4152)

The config thinks has_country_flag and set_ruler is used in a province and trade node scope for some reason even though new_tag is a country scope:
![Screenshot 2023-05-15 165855](https://github.com/cwtools/cwtools-eu4-config/assets/114454346/3d6af854-0de3-4119-892c-072c346104a5)
![Screenshot 2023-05-15 165910](https://github.com/cwtools/cwtools-eu4-config/assets/114454346/6bacf323-548d-45f5-a65a-77bb9709f629)

Lastly, if is unexpected in new_tag for some reason:
![Screenshot 2023-05-15 170410](https://github.com/cwtools/cwtools-eu4-config/assets/114454346/f74a5117-8579-4e80-89be-3c695b2e088d)

**Comment by EmperorNuclear** [comment]
All of this is in the context of a scripted effect, in case there was in any confusion about that.

**Comment by maxice8** [comment]
Can I get an example of the code triggering it ?

**Comment by EmperorNuclear** [comment]
This is a custom peace treaty.

```
# Seize the Iron Throne
po_seize_the_iron_throne = {
	category = 6
	power_projection = humiliated_rival
	power_cost_base = 1.0
	prestige_base = 0.5
	ae_base = 0.0
	requires_is_allowed = yes
	
	warscore_cost = {
		all_provinces = 0.0
		no_provinces = 100.0
		owner_keeps = 0.0
		conquered = 0.0
		returned_core = 0.0
		released_nation = 0.0
		cancelled_subject = 0.0
		concede_colonial_region = 0.0
	}
	
	is_visible = {
		always = yes
	}
	is_allowed = {
		always = yes
	}
	effect = {
		hidden_effect = {
			save_event_target_as = originalCOU
		}
		switch_tag_with_ruler = { # Change to Crownlands country
			ruler_string = King_of_Andals
			consort_string = Queen_of_Andals
			heir_string = Heir_of_Andals
			new_tag = FROM
		}
		save_global_event_target_as = IronThroneKing
		create_union = event_target:originalCOU
		every_country = {
			limit = {
				is_part_of_hre = yes
			}
			add_aggressive_expansion = {
				who = FROM
				value = 25
				apply_calc = yes
			}
		}
	}
	ai_weight = {
		export_to_variable = {
			variable_name = ai_value
			value = 100
		}
	}
}
```

**Comment by EmperorNuclear** [comment]
This is the actual scripted effect.

```
switch_tag_with_ruler = {
	exile_ruler_as = {
		name = $ruler_string$
		kill_monarch = no 
	}
	if = {
		limit = {
			has_consort = yes
		}
		exile_consort_as = $consort_string$
		$new_tag$ = {
			set_country_flag = consort_exists
		}
	}
	if = {
		limit = {
			has_heir = yes
		}
		exile_heir_as = $heir_string$
		$new_tag$ = {
			set_country_flag = heir_exists
		}
	}
	switch_tag = $new_tag$
	$new_tag$ = {
		set_ruler = $ruler_string$
		if = {
			limit = {
				has_country_flag = consort_exists
			}
			set_consort = $consort_string$
		}
		if = {
			limit = {
				has_country_flag = heir_exists
			}
			set_heir = $heir_string$
		}
	}
}
```

**Comment by maxice8** [comment]
This should be fixed by #289

**Comment by maxice8** [comment]
@17blue17 can I have permission to close issues ?

**Comment by 17blue17** [comment]
I don't know how to do that.  I will ask Caligula.

**Comment by maxice8** [comment]
@EmperorNuclear can you confirm the issue is solved ? I have pushed changes that should support the new modifiers

**Comment by EmperorNuclear** [comment]
Success, thank you big boss.

![Screenshot 2023-05-23 010509](https://github.com/cwtools/cwtools-eu4-config/assets/114454346/833eb34c-1134-4d1d-893c-a8fa5bcaffc4)
