### ISSUE TITLE
More False Notices

### ISSUE THREAD

**Issue by EmperorNuclear** [cwtools/cwtools-eu4-config#288]
is_city = no is unexpected apparently

![Screenshot 2023-05-16 012104](https://github.com/cwtools/cwtools-eu4-config/assets/114454346/b7ebac90-f1d4-4ab0-a2af-69101cc8ca2b)

**Comment by 17blue17** [comment]
Why would you use no?  If it is not a city then don't use is_city = yes.  I do not think paradox uses is_city = no

**Comment by 17blue17** [comment]
Correction I do see paradox using is_city = no.  I will fix.

**Comment by 17blue17** [comment]
My test shows is_city = no works, so there must be something else wrong in that history file causing cwtools to think you are not in province scope.  Sometimes, it gets stuck when a person is editing, and you have to close vs code and reopen.

**Comment by 17blue17** [comment]
is_city = no tested and works
