### ISSUE TITLE
00_diplomatic_actions.txt   stability_cost_to_declare_war shows as error 

### ISSUE THREAD

**Issue by 17blue17** [cwtools/cwtools-eu4-config#292]
is there something broken with the following trigger as stability_cost_to_declare_war shows as error in 00_diplomatic_actions.txt and it is correctly included in modifiers.   Is the #todo still todo?

## scope = country
###Returns true if the value of the specified modifier is at least X for the country.
alias[trigger:has_global_modifier_value] = {
	which = enum[modifiers] #todo
	value = float
	## cardinality = 0..1
![error1](https://github.com/cwtools/cwtools-eu4-config/assets/75548706/0033b082-cfb3-4808-b938-446046791db8)

	extra_shortcut = bool
}

**Comment by 17blue17** [comment]
I can try to fix but I wanted to ask first.

**Comment by maxice8** [comment]
line 1383 and 1496 were added by CaligulaCaesar as of ce5e1846

**Comment by 17blue17** [comment]
OK I will try to fix.  Didn't want to goof up anything you were working on.

**Comment by 17blue17** [comment]
updated enum to give it an unique name and added the missing modifier
