### ISSUE TITLE
Conditional generic scripted effect params

### ISSUE THREAD

**Issue by sushiinudesu** [cwtools/cwtools-eu4-config#328]
U can create an effect with a conditional generic param like this:
```
hex_set_heir = { 
         [[chef] 
                 define_heir = { 
                         name = "Chef" 
                         dynasty = "'the Cauldron Master'" 
                         birth_date = 2.1.1 
                         claim = 50 
                 } 
         ]
}
```

And then use it it somewhere like
```
hex_set_heir = { chef = yes }
```

CW Tools marks it as error, but this seems to be a perfectly valid code.
Dunno if u accept issues that are not vanilla, but still working. Kinda not familiar how to code this, but I have a few other suggestions that I might be able to code.

**Comment by 17blue17** [comment]
Hello.  CW tools is not able to process [[ ] code and the author is unable to fix this.  I have this listed on the eu4 forum cwtools thread as a known issue.

Best Wishes

**Comment by sushiinudesu** [comment]
Unfortunate. Oh well, I guess my perfectionism will make me rewrite the code a bit to avoid the warnings)
