### ISSUE TITLE
Simpler variable functions

### ISSUE THREAD

**Issue by sushiinudesu** [cwtools/cwtools-eu4-config#344]
Anbennar seems to have a more compact way to write `check_variable` and others:

``` 
REB = { check_variable = { nbExpedition = 1 } }
```

No which, no value. I guess it's working, so maybe it's smth worth checking.

**Comment by 17blue17** [comment]
I had a discussion with Paradox staff recently on using change_variable without using which and they confirmed it worked and I fixed that.  I guess if you are saying check_variable works the same?   What about set_variable or anything else similar I should also change?????

**Comment by 17blue17** [comment]
I will do a pull request for check_variable.   I did one test and it appears to work but please double check it yourself.

**Comment by 17blue17** [comment]
done

**Comment by 17blue17** [comment]
can someone explain why it works in church aspects but it errors in ages for reformation????   What is wrong with the ages reformation.   Help??????????????????

**Comment by sushiinudesu** [comment]
I added a new PR with stuff that removes errors in Anbennar code - https://github.com/cwtools/cwtools-eu4-config/pull/346
Not sure if all of it works, just what Anbennar has errors with

**Comment by sushiinudesu** [comment]
> can someone explain why it works in church aspects but it errors in ages for reformation???? What is wrong with the ages reformation. Help??????????????????

I believe this is cause `num_converted_religion` is never set.

**Comment by 17blue17** [comment]
I have made and merged PR's to hopefully handle the items in this issue.  If everything is good then please close otherwise tell me what is left to do.
