### ISSUE TITLE
has_global_modifier_value options

### ISSUE THREAD

**Issue by sushiinudesu** [cwtools/cwtools-eu4-config#349]
More options are used as which in `has_global_modifier_value` in Anbennar. Probably all are working, cause they are used everywhere (224 errors total)

```
num_accepted_cultures
movement_speed
fire_damage
shock_damage
trade_efficiency
local_build_time
global_missionary_strength
local_development_cost
global_spy_defence
global_ship_trade_power
local_institution_spread
global_manpower
spy_offence
trade_steering
prestige
tolerance_own
siege_ability
```

**Comment by 17blue17** [comment]
done.  will post PR shortly.   Also will do PR for the additional export to variable additions you posted separately on PR 346.

**Comment by 17blue17** [comment]
done
