### ISSUE TITLE
building scope should allow "indestructible" tag

### ISSUE THREAD

**Issue by zebh** [cwtools/cwtools-eu4-config#60]
Found this when looking through mod files for the mod "Anbennar",

According to https://eu4.paradoxwikis.com/Building_modding the building scope should allow an optional `indestructible = <bool>` tag which hints the game to exempt it from being removed during bankruptcy.

Currently cwtools gives `CW262` for these.

**Comment by 17blue17** [comment]
Will add.  Note it is best to leave requests on the eu4 Paradox forum cwtools thread as I check there often.  I did not even know this issues thread on github existed.
